name: inpaint_train
channels:
- pytorch
- defaults
dependencies:
- python=3.6
- pytorch=1.3.1
- scipy
- pip
- pip:
  - torchvision==0.4.1
  - tensorboardX==2.0
  - pyyaml==5.4.1
  - onnx==1.8.0
  - onnxruntime==1.1.2
  - onnxruntime-tools==1.7.0
  - sympy==1.9