name: inpaint_test
channels:
- pytorch
- defaults
dependencies:
- python
- pytorch
- scipy
- pip
- pip:
  - torchvision
  - tensorboardX
  - pyyaml
  - onnx
  - onnxruntime
  - onnxruntime-tools
  - sympy