name: pix2pix
channels:
- pytorch
- nvidia
- defaults
dependencies:
- python
- pytorch
- pytorch-cuda
- scipy
- pip
- pip:
  - torchvision
  - pillow
  - numpy
  - opencv-python
  - onnx
  - onnxruntime
  - onnxruntime-tools
  - sympy
